# This is a config for E2B sandbox template.
# You can use template ID (821axfaofidldkbga4jg) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("821axfaofidldkbga4jg") # Sync sandbox
# sandbox = await AsyncSandbox.create("821axfaofidldkbga4jg") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('821axfaofidldkbga4jg')

team_id = "9bf32b56-0b1d-4ee6-86d5-765d23ed0ebf"
memory_mb = 4_096
cpu_count = 4
dockerfile = "e2b.Dockerfile"
template_id = "821axfaofidldkbga4jg"
